import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Scale, AlertCircle, CheckCircle, Clock, Eye } from "lucide-react";
const biasMetrics = [
    { name: "Geographic Distribution", value: 92, status: "good", description: "Risk alerts evenly distributed across demographics" },
    { name: "Socioeconomic Balance", value: 88, status: "good", description: "No correlation between income levels and flag rates" },
    { name: "Temporal Fairness", value: 95, status: "good", description: "Consistent prediction quality across all time periods" },
    { name: "Historical Bias Correction", value: 84, status: "warning", description: "Minor adjustment needed for pre-2020 training data" }
];
const zoneCategories = [
    { category: "Commercial", zones: 4, avgRisk: 62, alerts: 8, population: "Low" },
    { category: "Residential", zones: 6, avgRisk: 34, alerts: 4, population: "High" },
    { category: "Industrial", zones: 3, avgRisk: 58, alerts: 5, population: "Low" },
    { category: "Mixed Use", zones: 5, avgRisk: 48, alerts: 6, population: "Medium" },
    { category: "Entertainment", zones: 2, avgRisk: 71, alerts: 7, population: "Variable" }
];
const auditLog = [
    { id: 1, timestamp: "2024-01-15 14:32:18", action: "Prediction Generated", zone: "Downtown Core", details: "Risk level: 87%, Confidence: 94%", reviewer: "System" },
    { id: 2, timestamp: "2024-01-15 14:30:45", action: "Bias Check Passed", zone: "All Zones", details: "Daily fairness audit completed", reviewer: "Auto-audit" },
    { id: 3, timestamp: "2024-01-15 14:28:12", action: "Manual Override", zone: "University Quarter", details: "Risk downgraded: Special event context", reviewer: "Capt. Johnson" },
    { id: 4, timestamp: "2024-01-15 14:25:33", action: "Prediction Generated", zone: "Financial Hub", details: "Risk level: 79%, Confidence: 89%", reviewer: "System" },
    { id: 5, timestamp: "2024-01-15 14:22:08", action: "Model Retrained", zone: "Global", details: "Incorporated 2,400 new outcomes", reviewer: "ML Pipeline" },
    { id: 6, timestamp: "2024-01-15 14:18:55", action: "Alert Dispatched", zone: "Industrial District", details: "Patrol unit notified", reviewer: "Dispatcher AI" },
    { id: 7, timestamp: "2024-01-15 14:15:22", action: "Feedback Received", zone: "Harbor Area", details: "Prediction confirmed: False positive", reviewer: "Officer Martinez" }
];
export default function FairnessDashboard() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 rounded-lg bg-green-500/20", children: _jsx(Scale, { className: "w-6 h-6 text-green-400" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white", children: "Fairness & Transparency" }), _jsx("p", { className: "text-slate-400 text-sm", children: "Ethical AI monitoring and audit trail" })] })] }), _jsxs("div", { className: "rounded-2xl bg-slate-900/50 border border-slate-800 overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-slate-800 flex items-center justify-between", children: [_jsx("h3", { className: "font-semibold text-white", children: "Bias Detection Meters" }), _jsxs("div", { className: "flex items-center gap-2 text-xs text-green-400", children: [_jsx(CheckCircle, { className: "w-4 h-4" }), _jsx("span", { children: "All metrics within acceptable range" })] })] }), _jsx("div", { className: "p-6 grid grid-cols-1 md:grid-cols-2 gap-6", children: biasMetrics.map((metric, index) => (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: index * 0.1 }, className: "p-4 rounded-xl bg-slate-800/50 border border-slate-700", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("span", { className: "font-medium text-white", children: metric.name }), _jsxs("div", { className: `flex items-center gap-1.5 px-2 py-1 rounded-full text-xs ${metric.status === "good"
                                                ? "bg-green-500/20 text-green-400"
                                                : "bg-yellow-500/20 text-yellow-400"}`, children: [metric.status === "good" ? _jsx(CheckCircle, { className: "w-3 h-3" }) : _jsx(AlertCircle, { className: "w-3 h-3" }), metric.status === "good" ? "Healthy" : "Needs Review"] })] }), _jsxs("div", { className: "relative mb-2", children: [_jsx("div", { className: "w-full h-3 bg-slate-700 rounded-full overflow-hidden", children: _jsx(motion.div, { className: `h-full rounded-full ${metric.value >= 90 ? "bg-green-500" :
                                                    metric.value >= 80 ? "bg-yellow-500" : "bg-red-500"}`, initial: { width: 0 }, animate: { width: `${metric.value}%` }, transition: { delay: index * 0.1 + 0.3, duration: 0.5 } }) }), _jsxs("span", { className: "absolute right-0 top-1/2 -translate-y-1/2 text-sm font-bold text-white", children: [metric.value, "%"] })] }), _jsx("p", { className: "text-xs text-slate-400", children: metric.description })] }, metric.name))) })] }), _jsxs("div", { className: "rounded-2xl bg-slate-900/50 border border-slate-800 overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-slate-800", children: [_jsx("h3", { className: "font-semibold text-white", children: "Risk Distribution by Zone Category" }), _jsx("p", { className: "text-xs text-slate-500 mt-0.5", children: "Ensuring equitable risk assessment across different area types" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-700", children: [_jsx("th", { className: "text-left py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Category" }), _jsx("th", { className: "text-center py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Zones" }), _jsx("th", { className: "text-center py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Avg Risk" }), _jsx("th", { className: "text-center py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Active Alerts" }), _jsx("th", { className: "text-center py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Population Density" }), _jsx("th", { className: "text-center py-3 px-4 text-xs font-semibold text-slate-400 uppercase", children: "Distribution" })] }) }), _jsx("tbody", { children: zoneCategories.map((cat, index) => (_jsxs(motion.tr, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: index * 0.05 }, className: "border-b border-slate-800/50", children: [_jsx("td", { className: "py-3 px-4 font-medium text-white", children: cat.category }), _jsx("td", { className: "py-3 px-4 text-center text-slate-300", children: cat.zones }), _jsx("td", { className: "py-3 px-4 text-center", children: _jsxs("span", { className: `font-medium ${cat.avgRisk >= 60 ? "text-orange-400" :
                                                        cat.avgRisk >= 40 ? "text-yellow-400" : "text-green-400"}`, children: [cat.avgRisk, "%"] }) }), _jsx("td", { className: "py-3 px-4 text-center text-slate-300", children: cat.alerts }), _jsx("td", { className: "py-3 px-4 text-center text-slate-300", children: cat.population }), _jsx("td", { className: "py-3 px-4", children: _jsx("div", { className: "w-full h-2 bg-slate-700 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full bg-cyan-500 rounded-full", style: { width: `${(cat.zones / 20) * 100}%` } }) }) })] }, cat.category))) })] }) })] }), _jsxs("div", { className: "rounded-2xl bg-slate-900/50 border border-slate-800 overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-slate-800 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Eye, { className: "w-5 h-5 text-cyan-400" }), _jsx("h3", { className: "font-semibold text-white", children: "Prediction Audit Log" })] }), _jsx("span", { className: "text-xs text-slate-400", children: "Last 24 hours" })] }), _jsx("div", { className: "divide-y divide-slate-800/50", children: auditLog.map((entry, index) => (_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: index * 0.05 }, className: "p-4 hover:bg-slate-800/30 transition-colors", children: _jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "p-2 rounded-lg bg-slate-800 mt-0.5", children: _jsx(Clock, { className: "w-4 h-4 text-slate-400" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-white text-sm", children: entry.action }), _jsx("p", { className: "text-xs text-slate-400 mt-0.5", children: entry.details }), _jsxs("div", { className: "flex items-center gap-3 mt-2 text-xs", children: [_jsx("span", { className: "text-cyan-400", children: entry.zone }), _jsx("span", { className: "text-slate-600", children: "\u2022" }), _jsx("span", { className: "text-slate-500", children: entry.reviewer })] })] })] }), _jsx("span", { className: "text-xs text-slate-500 whitespace-nowrap", children: entry.timestamp })] }) }, entry.id))) })] })] }));
}
